server:
  port: 8000

spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:5012;databaseName=master;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
    queue:
      json-name: test.json
      dto-name: test.dto
    exchange:
      json-name: json.topic
      dto-name: dto.topic
    routing:
      key: test

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# springdoc:
#  swagger-ui:
#    # swagger-ui ?? ??. default ?? /swagger-ui.html??.
#    path: /swagger-custom-ui.html
#
#    # ? API? ?? ?? ??
#    # path, query, body, response ??? ??
#    groups-order: DESC
#
#    # ?? ?? ??.
#    # alpha: ??? ? ??
#    # method: OpenAPI specification file? ??? ?? ?? ?? ?? ??
#    tags-sorter: alpha
#
#    # ???? ?? ??.
#    # method? delete - get - patch - post - put ??? ????.
#    # alpha? ??? ??? ??? ??? ? ??.
#    operations-sorter: method
#
#    # swagger-ui default url? petstore html? ???? ??
#    disable-swagger-default-url: true
#
#    # swagger-ui?? try ?? ? request duration? ???? ??
#    display-request-duration: true
#
#  # openAPI ?? ??. default ?? /v3/api-docs ??.
#  api-docs:
#    path: /api-docs
#
#  # Spring Actuator? endpoint?? ??? ????
#  show-actuator: true
#
#  # request media type ? ?? ?
#  default-consumes-media-type: application/json
#
#  # response media type ? ?? ?
#  default-produces-media-type: application/json
#
#  # ?? ??? ???? controller? swagger-ui? ????.
#  paths-to-match:
#    - /api/**